apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uit-go-core-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UIT-GO/gitops-repo
    targetRevision: main
    path: core-services
  destination:
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true