apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uit-go
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mainguyenuit/uit-go-gitops.git
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: uit-go
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
